FROM python:3.10.4-bullseye
RUN python -m pip install --upgrade pip

#WORKDIR mkdir and cd - unsure if first one is necessary?
#WORKDIR /container/whatever
COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt
WORKDIR /app

# I believe that the command below runs fastapi
CMD uvicorn main:app --reload --host 0.0.0.0