volumes:
  ourspace:
    external: true
  pg-admin:
    external: true
services:
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh # runs run.sh file, change script in package.json
    working_dir: /app
    volumes:
      - ./ghi/app:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API_HOST: http://localhost:8000
  reviews:
    build:
      context: ./reviews/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8070:8000"
    volumes:
      - ./reviews/api:/app
    environment:
      PGHOST: db
      PGDATABASE: ourspace
      PGUSER: ourspace
      PGPASSWORD: ourspace
  forum:
    build:
      context: ./forum/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8090:8000"
    volumes:
      - ./forum/api:/app
    environment:
      PGHOST: db
      PGDATABASE: ourspace
      PGUSER: ourspace
      PGPASSWORD: ourspace
  jobs:
    build:
      context: ./jobs/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./jobs/api:/app
    environment:
      PGHOST: db
      PGDATABASE: ourspace
      PGUSER: ourspace
      PGPASSWORD: ourspace
      ADZUNA_API_KEY: ${ADZUNA_API_KEY}
      ADZUNA_APP_ID: ${ADZUNA_APP_ID}
  mentorship:
    build:
      context: ./mentorship/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8050:8000"
    volumes:
      - ./mentorship/api:/app
    environment:
      PGHOST: db
      PGDATABASE: ourspace
      PGUSER: ourspace
      PGPASSWORD: ourspace
  events:
    build:
      context: ./events/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./events/api:/app
    environment:
      #host is the name of the service running pgsequal
      PGHOST: db
      PGDATABASE: ourspace
      PGUSER: ourspace
      PGPASSWORD: ourspace
  db:
    image: postgres:14.2-bullseye
    volumes:
      #for your initialization scripts
      - ./data/postgres/init:/docker-entrypoint-initdb.d
      # For the data stored by PostgreSQL
      - ourspace:/var/lib/postgresql/data
    environment:
      #for the superuser of postgres instance- must be same as above
      # Password for the postgres superuser
      # See 01-create-databases.sql for the name/password
      #   for the user of the application database
      POSTGRES_PASSWORD: ourspace
    ports:
      - "15432:5432"
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ourspace@example.com
      PGADMIN_DEFAULT_PASSWORD: ourspace
      PGADMIN_DISABLE_POSTFIX: 1
