volumes:
  ourspace:
    external: true
  pg-admin:
    external: true
services:
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh # runs run.sh file, change script in package.json
    working_dir: /app
    volumes:
      - ./ghi/app:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_ACCOUNTS_HOST: http://localhost:9000
      REACT_APP_EVENTS_HOST: http://localhost:8000
      REACT_APP_FORUM_HOST: http://localhost:8090
      REACT_APP_API_HOST: http://localhost:8000

  accounts:
    build:
      context: ./accounts/api
      dockerfile: Dockerfile.dev
    ports:
      - "9000:8000"
    volumes:
      - ./accounts/api:/app
    environment:
      PGHOST: db #server that rdbms is running on- same for all
      PGDATABASE: accounts
      PGUSER: ourspace
      PGPASSWORD: ourspace
      SECRET_KEY: 1435e80f9a1c4c54a59f27d42743e016356036c4a0d955e0cd56318af53be578
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
      #host is the name of the service running pgsequal
  reviews:
    build:
      context: ./reviews/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8070:8000"
    volumes:
      - ./reviews/api:/app
    environment:
      PGHOST: db
      PGDATABASE: reviews
      PGUSER: ourspace
      PGPASSWORD: ourspace
      SECRET_KEY: 1435e80f9a1c4c54a59f27d42743e016356036c4a0d955e0cd56318af53be578

  forum:
    build:
      context: ./forum/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8090:8000"
    volumes:
      - ./forum/api:/app
    environment:
      PGHOST: db
      PGDATABASE: forum
      PGUSER: ourspace
      PGPASSWORD: ourspace
      SECRET_KEY: 1435e80f9a1c4c54a59f27d42743e016356036c4a0d955e0cd56318af53be578
  jobs:
    build:
      context: ./jobs/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./jobs/api:/app
    environment:
      PGHOST: db
      PGDATABASE: jobs
      PGUSER: ourspace
      PGPASSWORD: ourspace
      ADZUNA_API_KEY: ${ADZUNA_API_KEY}
      ADZUNA_APP_ID: ${ADZUNA_APP_ID}
      SECRET_KEY: 1435e80f9a1c4c54a59f27d42743e016356036c4a0d955e0cd56318af53be578
  mentorship:
    build:
      context: ./mentorship/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8050:8000"
    volumes:
      - ./mentorship/api:/app
    environment:
      PGHOST: db
      PGDATABASE: mentorship
      PGUSER: ourspace
      PGPASSWORD: ourspace
      SECRET_KEY: 1435e80f9a1c4c54a59f27d42743e016356036c4a0d955e0cd56318af53be578
  accounts-poller:
    build:
      context: ./accounts/api/poller
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./accounts/api/poller:/app
    depends_on:
      - db
      - accounts
    environment:
      PGHOST: db
      PGDATABASE: accounts
      PGUSER: ourspace
      PGPASSWORD: ourspace
  events:
    build:
      context: ./events/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./events/api:/app
    environment:
      #host is the name of the service running pgsequal
      PGHOST: db
      PGDATABASE: events
      PGUSER: ourspace
      PGPASSWORD: ourspace
      DJWTO_SIGNING_KEY: 1435e80f9a1c4c54a59f27d42743e016356036c4a0d955e0cd56318af53be578
  db:
    image: postgres:14.2-bullseye
    volumes:
      #for your initialization scripts
      - ./data/postgres/init:/docker-entrypoint-initdb.d
      # For the data stored by PostgreSQL
      - ourspace:/var/lib/postgresql/data
    environment:
      #for the superuser of postgres instance- must be same as above
      # Password for the postgres superuser
      # See 01-create-databases.sql for the name/password
      #   for the user of the application database
      POSTGRES_PASSWORD: ourspace
    ports:
      - "15432:5432"
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ourspace@example.com
      PGADMIN_DEFAULT_PASSWORD: ourspace
      PGADMIN_DISABLE_POSTFIX: 1
